cmake_minimum_required(VERSION 3.16.0 FATAL_ERROR)

#set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")

set(VERSION "1.2")

set(LANGUAGES )
if (APPLE)
    list(APPEND LANGUAGES "C")
    list(APPEND LANGUAGES "CXX")
    list(APPEND LANGUAGES "OBJC")
    list(APPEND LANGUAGES "OBJCXX")
    if ("${CMAKE_GENERATOR}" STREQUAL "Xcode")
        execute_process(COMMAND uname -m OUTPUT_VARIABLE UNAME_M ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        if (NOT "$ENV{SYSROOT}" STREQUAL "")
            set(SYSROOT "$ENV{SYSROOT}")
        else()
            execute_process(COMMAND xcodebuild -version -sdk macosx Path OUTPUT_VARIABLE SYSROOT ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        endif()
        if (NOT EXISTS "${SYSROOT}")
            message(FATAL_ERROR "SYSROOT does not exist!")
        endif()
        set(CMAKE_OSX_SYSROOT "${SYSROOT}")
        if ("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
            if ("${UNAME_M}" MATCHES "arm")
                set(CMAKE_OSX_ARCHITECTURES "arm64")
            else()
                set(CMAKE_OSX_ARCHITECTURES "$(ARCHS_STANDARD)")
            endif()
        endif()
    endif()
else()
    list(APPEND LANGUAGES "C")
    list(APPEND LANGUAGES "CXX")
    if (WINDOWS)
        list(APPEND LANGUAGES "RC")
    endif()
endif()

project(WaveEditProject VERSION ${VERSION} LANGUAGES ${LANGUAGES})

set(DEF )
set(LIB )
set(LIB_DIR "${CMAKE_CURRENT_LIST_DIR}/dep/lib")
set(SRC_DIR "${CMAKE_CURRENT_LIST_DIR}/src")

find_package(Threads REQUIRED)
find_package(OpenGL REQUIRED)
if (APPLE)
    find_package(SampleRate REQUIRED)
    find_package(SndFile REQUIRED)
    find_package(SDL2 REQUIRED)
else()
    set(OUTPUTS )
    list(APPEND OUTPUTS "${CMAKE_CURRENT_LIST_DIR}/dep/include/samplerate.h")
    list(APPEND OUTPUTS "${CMAKE_CURRENT_LIST_DIR}/dep/include/sndfile.h")
    list(APPEND OUTPUTS "${CMAKE_CURRENT_LIST_DIR}/dep/lib/libsamplerate.a")
    list(APPEND OUTPUTS "${CMAKE_CURRENT_LIST_DIR}/dep/lib/libsndfile.a")
    list(APPEND OUTPUTS "${CMAKE_CURRENT_LIST_DIR}/dep/lib/libSDL2.a")
    list(APPEND OUTPUTS "${CMAKE_CURRENT_LIST_DIR}/dep/lib/libSDL2main.a")
    add_custom_command(OUTPUT ${OUTPUTS} COMMAND "make" DEPENDS "${CMAKE_CURRENT_LIST_DIR}/dep/Makefile" COMMENT "Compile dependencies" WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/dep")
    add_library(samplerate STATIC IMPORTED)
    set_target_properties(samplerate PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/dep/lib/libsamplerate.a")
    add_library(sndfile STATIC IMPORTED)
    set_target_properties(sndfile PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/dep/lib/libsndfile.a")
    add_library(sdl STATIC IMPORTED)
    set_target_properties(sdl PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/dep/lib/libSDL2.a")
    add_library(sdlmain STATIC IMPORTED)
    set_target_properties(sdlmain PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/dep/lib/libSDL2main.a")
    list(APPEND LIB samplerate)
    list(APPEND LIB sndfile)
    list(APPEND LIB sdl)
    if (WINDOWS)
        list(APPEND LIB sdlmain)
    endif()
endif()

list(APPEND LIB Threads::Threads)
if (APPLE)
    list(APPEND LIB ${OPENGL_gl_LIBRARY})
else()
    list(APPEND LIB OpenGL::OpenGL)
endif()
if (TARGET SampleRate::samplerate)
    list(APPEND LIB SampleRate::samplerate)
else()
    list(APPEND LIB ${SAMPLERATE_LIBRARY})
endif()
if (TARGET SndFile::sndfile)
    list(APPEND LIB SndFile::sndfile)
else()
    list(APPEND LIB ${SNDFILE_LIBRARY})
endif()
if (TARGET SDL2::SDL2)
    list(APPEND LIB SDL2::SDL2)
else()
    list(APPEND LIB ${SDL2_LIBRARIES})
endif()

#file(GLOB SRC "${SRC_DIR}/**/*.c*")
file(GLOB SRC "${SRC_DIR}/*.c*")
file(GLOB INC "${SRC_DIR}/*.h*")
list(APPEND SRC ${INC})
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/pffft/pffft.h")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/pffft/pffft.c")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/lodepng/lodepng.h")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/lodepng/lodepng.cpp")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/imgui/imgui.h")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/imgui/imgui.cpp")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/imgui/imgui_draw.cpp")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/imgui/imgui_demo.cpp")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/imgui/examples/sdl_opengl2_example/imgui_impl_sdl.cpp")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/osdialog/osdialog.h")
list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/osdialog/osdialog.c")

if (APPLE)
    find_library(COCOA_LIBRARY_FRAMEWORK Cocoa)
    find_library(IOKIT_LIBRARY_FRAMEWORK IOKit)
    find_library(CORE_VIDEO_LIBRARY_FRAMEWORK CoreVideo)
    list(APPEND DEF "ARCH_MAC")
    list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/osdialog/osdialog_mac.m")
    list(APPEND LIB ${COCOA_LIBRARY_FRAMEWORK})
    list(APPEND LIB ${IOKIT_LIBRARY_FRAMEWORK})
    list(APPEND LIB ${CORE_VIDEO_LIBRARY_FRAMEWORK})
elseif (LINUX)
    find_package(PkgConfig REQUIRED)
    find_package(X11 REQUIRED)
    pkg_check_modules(GTK2 REQUIRED gtk+-2.0)
    pkg_check_modules(OGG REQUIRED ogg)
    pkg_check_modules(VORBIS REQUIRED vorbis)
    pkg_check_modules(VORBISENC REQUIRED vorbisenc)
    pkg_check_modules(FLAC REQUIRED flac)
    list(APPEND DEF "ARCH_LIN")
    list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/osdialog/osdialog_gtk2.c")
    list(APPEND LIB ${X11_LIBRARIES})
    list(APPEND LIB ${GTK2_LIBRARIES})
    list(APPEND LIB ${OGG_LIBRARIES})
    list(APPEND LIB ${VORBIS_LIBRARIES})
    list(APPEND LIB ${VORBISENC_LIBRARIES})
    list(APPEND LIB ${FLAC_LIBRARIES})
    include_directories(${X11_INCLUDE_DIRS})
    include_directories(${GTK2_INCLUDE_DIRS})
    include_directories(${OGG_INCLUDE_DIRS})
    include_directories(${VORBIS_INCLUDE_DIRS})
    include_directories(${VORBISENC_INCLUDE_DIRS})
    include_directories(${FLAC_INCLUDE_DIRS})
elseif (WINDOWS)
    list(APPEND DEF "ARCH_WIN")
    list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/ext/osdialog/osdialog_win.c")
    list(APPEND SRC "${CMAKE_CURRENT_LIST_DIR}/info.rc")
endif()

include_directories("${SRC_DIR}")
include_directories("${SRC_DIR}/..")
include_directories("${CMAKE_CURRENT_LIST_DIR}/dep")
include_directories("${CMAKE_CURRENT_LIST_DIR}/dep/include")
include_directories("${CMAKE_CURRENT_LIST_DIR}/dep/include/SDL2")
include_directories("${CMAKE_CURRENT_LIST_DIR}/ext")
include_directories("${CMAKE_CURRENT_LIST_DIR}/ext/imgui")
include_directories(${OPENGL_INCLUDE_DIRS})
include_directories(${OPENGL_INCLUDE_DIR})
include_directories(${SDL2_INCLUDE_DIR})

if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    list(APPEND DEF "DEBUG")
endif()
list(APPEND DEF "PFFFT_SIMD_DISABLE")
list(APPEND DEF "VERSION=${VERSION}")

add_executable(WaveEdit ${SRC})
if (APPLE)
    #set_target_properties(WaveEdit PROPERTIES BUNDLE true BUNDLE_EXTENSION app MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_LIST_DIR}/Info.plist" XCODE_ATTRIBUTE_INFOPLIST_FILE "${CMAKE_CURRENT_LIST_DIR}/Info.plist")
    add_custom_command(TARGET WaveEdit POST_BUILD COMMAND ${CMAKE_INSTALL_NAME_TOOL} -add_rpath "@executable_path/" $<TARGET_FILE:WaveEdit> || :)
endif()
set_target_properties(WaveEdit PROPERTIES LINKER_LANGUAGE CXX)
target_compile_definitions(WaveEdit PRIVATE ${DEF})
target_compile_features(WaveEdit PRIVATE cxx_std_11)
target_link_directories(WaveEdit PRIVATE ${LIB_DIR})
target_link_libraries(WaveEdit PRIVATE ${LIB})
install(TARGETS WaveEdit RUNTIME DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" BUNDLE DESTINATION "${CMAKE_INSTALL_PREFIX}/bin")

